version: "3.3"

services:
  fluentbit:
    image: fluent/fluent-bit
    restart: unless-stopped
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - "./conf:/fluentbit/conf"
    command: ["/fluent-bit/bin/fluent-bit", "-c", "/fluentbit/conf/fluentbit.conf"]
    logging:
      driver: "json-file"
