version: "3.3"

services:
  postgresdb:
    image: postgres
    restart: always
    networks:
      - web
    ports:
      - 5432:5432
    environment: 
      POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}
    logging:
      driver: "fluentd"
  
  adminer:
    image: adminer
    restart: always
    networks:
      - web
    labels:
      - "traefik.enable=true"
      
      - "traefik.http.routers.adminer_http.rule=Host(`adminer.${DOCKER_BASE_DOMAIN}`)"
      - "traefik.http.routers.adminer_http.entrypoints=web"
      - "traefik.http.routers.adminer_http.middlewares=redirect-https-adminer"

      - "traefik.http.middlewares.redirect-https-adminer.redirectscheme.scheme=https"

      - "traefik.http.routers.adminer_https.rule=Host(`adminer.${DOCKER_BASE_DOMAIN}`)"
      - "traefik.http.routers.adminer_https.entrypoints=web-secured"
      - "traefik.http.routers.adminer_https.tls=true"
      - "traefik.http.routers.adminer_https.tls.certresolver=resolver"
      
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"

networks:
  web:
    external: true